version: '3.3' 

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        ports:
            - "9200:9200"
            - "9300:9300"
        configs:
            - source: elasticsearch_config
              target: /usr/share/elasticsearch/config/elasticsearch.yml
        volumes:
            - esdata:/usr/share/elasticsearch/data
        networks:
            - elk
    
    kibana:
        image: docker.elastic.co/kibana/kibana:6.5.4
        ports:
            - "5601:5601"
        configs:
            - source: kibana_config
              target: /usr/share/kibana/config/kibana.yml
        networks:
            - elk
        depends_on:
            - elasticsearch
              
    logstash:
        image: docker.elastic.co/logstash/logstash:6.5.4
        volumes:
            - /tmp/pipeline:/usr/share/logstash/pipeline/
            - /tmp/input:/tmp/input
        ports:
            - "5000:5000"
            - "9600:9600"
        configs:
            - source: logstash_config
              target: /usr/shate/logstash/config/logstash.yml
            - source: logstash_pipeline 
              target: /usr/share/logstash/pipeline/logstash.conf
        networks:
            - elk
        depends_on:
            - elasticsearch

volumes:
    esdata:
        driver: local

networks:
    elk:
       driver: bridge

configs:
    elasticsearch_config: 
        file: ./elasticsearch/config/elasticsearch.yml
    kibana_config:
        file: ./kibana/config/kibana.yml
    logstash_config:
        file: ./logstash/config/logstash.yml
    logstash_pipeline:
        file: ./logstash/pipeline/logstash.conf
