version: '3.3'

services:

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
        ports:
            - "9200:9200"
            - "9300:9300"
<<<<<<< HEAD
#        configs:
#            - source: elasticsearch_config
#              target: /usr/share/elasticsearch/config/elasticsearch.yml
=======
>>>>>>> fix
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elaticsearch.yml:ro
            # - esdata:/usr/share/elasticsearch/data
        networks:
            - elk

    kibana:
        image: docker.elastic.co/kibana/kibana:${TAG}
        ports:
            - "5601:5601"
<<<<<<< HEAD
#        configs:
#            - source: kibana_config
#              target: /usr/share/kibana/config/kibana.yml
=======
        volumes:
            - ./kibana/config/:/usr/share/kibana/config:ro
>>>>>>> fix
        networks:
            - elk
        depends_on:
            - elasticsearch

    logstash:
        image: docker.elastic.co/logstash/logstash:${TAG}
        ports:
            - "5000:5000"
            - "9600:9600"
<<<<<<< HEAD
#        configs:
#            - source: logstash_config
#              target: /usr/shate/logstash/config/logstash.yml
#            - source: logstash_pipeline 
#              target: /usr/share/logstash/pipeline/logstash.conf
=======
        volumes:
            - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
            - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
>>>>>>> fix
        networks:
            - elk
        depends_on:
            - elasticsearch

volumes:
    esdata:
        driver: local

networks:
    elk:
       driver: bridge
