version: '3.3'

services:

    web:
        image: nginx:1.14-alpine
        volumes:
            - ./.docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - "80:80"
        depends_on:
            - php
            - db

    php:
        build: .docker
        volumes:
            - ./.docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - .:/var/www/html

    db:
        image: postgres:11-alpine
        environment:
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=dbuser
        ports:
            - "5432:5432"
        volumes:
            - ./config/postgres/:/docker-entrypoint-initdb.d/

